#pragma once
#include "npch.h"

namespace Nova::input {

	enum class Key {
		NONE = 0,

		LSHIFT = 1, LCTRL, LALT, RSHIFT, RCTRL, ALTGR, LSUPER, RSUPER,
		BACKSPACE, TAB, ENTER, ESCAPE, INSERT, DELETE, PGUP, PGDN, END, HOME,
		LEFT, UP, RIGHT, DOWN, CAPS_LOCK, SCROLL_LOCK, NUM_LOCK, PRINT_SCREEN, PAUSE,
		LMENU, RMENU,

		N0 = 48, N1, N2, N3, N4, N5, N6, N7, N8, N9,
		A = 65, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
		SPACE = 32, HASH = 35, APOSTROPHE = 39, COMMA = 44, MINUS, PERIOD, SLASH, SEMICOLON = 59,
		EQUAL = 61, LBRACKET = 91, BACKSLASH, RBRACKET, GRAVE_ACCENT = 96,

		F1 = 97, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24, F25, F26,

		KP_0, KP_1, KP_2, KP_3, KP_4, KP_5, KP_6, KP_7, KP_8, KP_9,
		KP_DIVIDE, KP_MULTIPLY, KP_SUBTRACT, KP_ADD, KP_ENTER, KP_PERIOD,
		KP_HOME, KP_UP, KP_PGUP, KP_LEFT, KP_RIGHT, KP_END, KP_DOWN, KP_PGDN, KP_INSERT, KP_DELETE,

		COUNT
	};

}